STATUS_EXIT = 0
STATUS_CONNECTED = 1
STATUS_LOGIN_FAIL = 2
STATUS_CHOOSE_GAME = 3
STATUS_GAME_SELECTED = 4
STATUS_POSITION_SHIPS = 5
STATUS_USER_READY = 6
STATUS_SHOOTING = 7
STATUS_WAITING = 8
NOTIFY_READY = 9
NOTIFY_ALL_READY = 10
NOTIFY_JOINED = 11
GAME_STARTED = 12
NOTIFY_HIT = 13
NOTHING = -1

FIELD_SHIP = '|#|'
FIELD_EMPTY = '|_|'
FIELD_MISS = '|o|'
FIELD_HIT = '|x|'

MSG_SEP = ':'