STATUS_EXIT = 0
STATUS_CONNECTED = 1
STATUS_LOGIN_FAIL = 2
STATUS_CHOOSE_GAME = 3
STATUS_GAME_SELECTED = 4
STATUS_POSITION_SHIPS = 5
STATUS_USER_READY = 6
STATUS_GAME_MODE = 7
NOTIFY_READY = 8
NOTIFY_JOINED = 9

FIELD_SHIP = '|#|'
FIELD_EMPTY = '|_|'
FIELD_MISS = '|o|'
FIELD_HIT = '|x|'

MSG_SEP = ':'